name: myschool
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  intl: ^0.19.0
  flutter_localizations:
        sdk: flutter
  shared_preferences: ^2.3.2
  http: ^1.2.2
  flutter_lints: ^4.0.0
  iconsax: ^0.0.8
  awesome_snackbar_content: ^0.1.4
  loading_animation_widget: ^1.2.1
  flutter_dotenv: ^5.1.0
  lottie: ^3.1.2
  appwrite: ^13.0.0
  get_storage: ^2.1.1
  flutter_animate: ^4.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  #------------- LOCAL ASSETS -------------#
  assets:
    - assets/images/png/
    - assets/lottie/
    - .env


  #------------- LOCAL FONTS -------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\poppins\Poppins-Thin.ttf
          weight: 100
        - asset: assets\fonts\poppins\Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets\fonts\poppins\Poppins-Light.ttf
          weight: 300
        - asset: assets\fonts\poppins\Poppins-Regular.ttf
          weight: 400
        - asset: assets\fonts\poppins\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\poppins\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\poppins\Poppins-Bold.ttf
          weight: 800
        - asset: assets\fonts\poppins\Poppins-ExtraBold.ttf
          weight: 900

flutter_intl:
  enabled: true
